# Algorithm PARAMETERS
# Classical ARM
MIN_SUPPORT: 0.04
MIN_CONFIDENCE: 0.8

# Optimization-based ARM
INIT_POPULATION_SIZE: 100
MAX_EVALS: 50000

# DL-based ARM
# ARM-AE
LIKENESS: 0.5
NUMBER_OF_RULES: 2

# AE SemRL
SIMILARITY_THRESHOLD: 0.8
NOISE_FACTOR: 0.5

# Generic to DL-based ARM
EPOCHS: 10
BATCH_SIZE: 256
LEARNING_RATE: 1e-4
NUMBER_OF_ANTECEDENTS: 2

# Generic
NUM_OF_RUNS: 6
